version: '2'

services:
    linux:
        # name: mnt_linux
        build: ./build
        volumes:
                - "./conf:/tmp/conf"
                - "./share:/tmp/share"
        ports:
            - "2229:22"

